
spring:
  application:
    name: enjoytrip
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssafytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
    
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.enjoytrip.dto
  
logging:
  level:
    root: debug
    com.ssafy.ws.step3: debug

jwt:
  secret: secretkesdgfsdgsfdgfsdgfdsgfsdgfdsgfdsgsdfgfsdgfsdgfdsgfdsgfdsgfdsgfdsfdasfdasfdasfdasfdasfadsfadsfdsafsafdsa
  token-validity-in-seconds: 3000

